### ISSUE TITLE
uma1.2.0版本标准模板，npm start 后http://127.0.0.1:8058/index/index 报错

### ISSUE THREAD

**Issue by gaogao2017** [Umajs/Umajs#67]
下载的官方标准模板
任何代码都没有修改
直接执行npm start 
访问http://127.0.0.1:8058/index/index 显示500 ERROR

![image](https://user-images.githubusercontent.com/26714881/126281421-73d34a92-b092-4940-9ae8-7fd39f5e857a.png)

**Comment by dazjean** [comment]
您好，请问选择的是哪一种模板类型呢？有问题我们今天内解决。

**Comment by dazjean** [comment]
@gaogao2017  问题已经修复  在即将发布的v2版本umajs中，我们将取消默认文件路由，所以建议在业务代码使用路由时，用@Path注册到使用的方法中
