### ISSUE TITLE
Vue3有计划支持吗？

### ISSUE THREAD

**Issue by 551685830** [Umajs/Umajs#88]
Vue3有计划支持吗？

**Comment by dazjean** [comment]
> Vue3有计划支持吗？

hi 新年好。目前vue3.0同构插件已经发布了一些时间了，https://github.com/Umajs/plugin-vue3-ssr，最近一段时间比较忙还没来得及补充文档，在节后我尽快补一下；使用方式和2.0版本插件几乎一样。有问题可及时联系微信 Da_ZJean

**Comment by yywang95** [comment]
感谢您的来信，您的邮件已收到，我会尽快查看并回复！
